import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import { MapPinIcon, Bars3Icon } from "@heroicons/react/24/solid";

const manropeFont = Manrope({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manropeFont.className} h-full`}
    >
      <body className="min-h-full flex flex-col">
        <header className="w-full px-6 pt-3 flex justify-between bg-fundo">
          <div className="flex gap-1.5">
            <div className="w-7 h-7 flex items-center justify-center rounded-full bg-azul">
            <MapPinIcon className="w-4 text-branco"></MapPinIcon>
            </div>
            <p className="text-branco text-xl font-extrabold">vagajá</p>
          </div>

          <div>
          <Bars3Icon className="w-8 text-branco"></Bars3Icon>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
