import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";

const manropeFont = Manrope({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manropeFont.className} h-full`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
