import type { Metadata } from "next";
import "./globals.css";
import { Manrope, Geist } from "next/font/google";
import { cn } from "@/src/lib/utils";
import Header from "../components/common/header";
import Footer from "../components/common/footer";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const manropeFont = Manrope({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", manropeFont.className, "font-sans", geist.variable)}>
      <body className="w-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
